import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner"



export const metadata: Metadata = {
  title: "盾构指挥中心-中铁二局城通公司",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ fontFamily: "var(--font-sans)" }}
        className="antialiased"
      >
        <Toaster richColors position="top-center" />
        {children}
      </body>
    </html>
  );
}

